### ISSUE TITLE
Sidebar menu links "Projects" "Tasks" etc - don't work: throw browser console error

### ISSUE THREAD

**Issue by PovilasKorop** [Bottelet/DaybydayCRM#155] opened 2020-07-08 05:30 UTC
Whenever I want to go from Dashboard to any menu item on the left (it seems), I see console error:

```
vendor.js:732 Uncaught TypeError: Cannot convert object to primitive value
    at RegExp.test (<anonymous>)
    at HTMLDivElement.<anonymous> (vendor.js:732)
    at Function.each (app.js:65534)
    at jQuery.fn.init.each (app.js:65356)
    at jQuery.fn.init.Plugin [as collapse] (vendor.js:727)
    at HTMLAnchorElement.<anonymous> (vendor.js:765)
    at HTMLDocument.dispatch (app.js:70582)
    at HTMLDocument.elemData.handle (app.js:70386)
```

See video: https://www.loom.com/share/5946accd32b043a5b0163f4280f54341

**Comment by Bottelet** [comment] 2020-07-08 14:55
Can you tell me if you are on docker?, and if not what version you are using node and NPM?

Also, there is a PR on it. Can you see if that works for you? 
https://github.com/Bottelet/DaybydayCRM/pull/150... I haven't merged it yet, as I can't reproduce the error.

**Comment by vitorfleite** [comment] 2020-07-08 14:57
My pull request fix this.

https://github.com/Bottelet/DaybydayCRM/pull/150

**Comment by Bottelet** [comment] 2020-07-08 15:08
@vitorfleite  can you tell me if this is happening with the docker setup? Or if you are running it local?

**Comment by vitorfleite** [comment] 2020-07-08 15:10
Local

**Comment by Bottelet** [comment] 2020-07-08 15:15
@vitorfleite What npm and node version and you running with local?

**Comment by PovilasKorop** [comment] 2020-07-08 16:46
@Bottelet I'm not on docker.

```
Povilass-MacBook-Pro:project2 povilas$ npm -v
6.4.1
Povilass-MacBook-Pro:project2 povilas$ node -v
v10.0.0
```

Sorry don't have enough time to try to test it from PR, maybe in a few days.

**Comment by Bottelet** [comment] 2020-07-08 20:48
This should have been fixed, seems like there is something that breaks it from node version 10.9.X and npm 6.12.X 
https://github.com/Bottelet/DaybydayCRM/pull/150

**Closed by Bottelet** 2020-07-08 20:48 UTC

**Comment by PovilasKorop** [comment] 2020-07-09 13:05
@Bottelet I can confirm it's fixed for me too.

**Comment by MakamuEvans** [comment] 2020-08-04 13:24
Does changing a generated file like vendor.js mean that everytime am running the npm dev/prod with changed code i'll have to keep editing the file?
